Feature/cesar guevara
makeitrealcamp/top-v17 pull request #4
Opened 2021-11-10 21:04 UTC by domakedev

### Descripción
Añadí la información de mi perfil.
...

### Feeling
[//]: <> (Como te sientes con este PR? la solucion que entregas como te hace sentir?)
- [x] 🤙 Solucion rapida
- [ ] 👌 Terminado y lsito
- [ ] 🤞 Espero que esto funcione, por favor revisar cuidadosamente

### Tickets
No hay ticket.

### Cómo probar?
No se puede.

### Screenshots (si es aplicable)
No hay.

### Scope

- [ ] 🐞 Bugfix (non-breaking changes que resuelve un problema
- [ ] 💚 Mejora (non-breaking change que agrega/modifica funcionalidad a una característica existente)
- [x] ⚡️ Nueva característica/feature (non-breaking change que agrega una nueva característica)
- [ ] ⚠️ Breaking change (cambio que no es compatible con versiones anteriores y/o cambia la funcionalidad actual)

2021-11-10 21:21 UTC, khriztianmoreno requested changes

2021-11-10 21:21 UTC, khriztianmoreno commented on profiles/cesar-guevara.md
> +💻 Electronic Engineer
Cesar por favor agrega la experiencia que tienes en los temas que estan en el archivo de ejemplo.

2021-11-10 22:26 UTC, domakedev commented on profiles/cesar-guevara.md
> +💻 Electronic Engineer
Listo, ya subi un nuevo commit con la información faltante. Gracias por el aviso.

2021-11-10 22:33 UTC, LordDoH approved these changes
Buen trabajo compañero!

2021-11-11 13:24 UTC, khriztianmoreno approved these changes
Buen trabajo.
![](https://media3.giphy.com/media/UmkNfWnDh8JYk/giphy.gif)

2021-11-11 13:35 UTC, merged